{% set name = "bids-validator" %}
{% set version = "1.14.7.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e6005a500b75f8a961593fb67d46085107dadb116f59a5c3b524aa0697945b66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer
  run:
    - python >={{ python_min }}
    - bidsschematools >=0.10

test:
  imports:
    - bids_validator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bids-standard/bids-validator
  summary: Validator for the Brain Imaging Data Structure
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - effigies
    - rwblair
    - sappelhoff
    - sarthakpati
