{% set name = "bids-validator" %}
{% set version = "1.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bids-validator-{{ version }}.tar.gz
  sha256: 7205ce4e68fba172215332c786f1ac1665025b702b6dff2b1e158f00a2df9890

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - bids_validator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bids-standard/bids-validator
  summary: Validator for the Brain Imaging Data Structure
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - effigies
    - rwblair
    - sappelhoff
    - sarthakpati
