{% set name = "bids-validator" %}
{% set version = "1.14.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: df2b6b5d1aaad61d34ccad0494f2ed73ce3082825ada31954c4e14c2538d485c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - versioneer
  run:
    - python >=3.6

test:
  imports:
    - bids_validator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bids-standard/bids-validator
  summary: Validator for the Brain Imaging Data Structure
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - effigies
    - rwblair
    - sappelhoff
    - sarthakpati
